#%RAML 1.0 NamedExample
value:

  - 
    CustomerID: 2345678901
    CustomerName: Raymond Mendoza
    CustomerName2: Bonn
    Street: Dela Rosa
    City: Makati
    PostalCode: 1230
    Country: PH
    Telephone:
    Currency: EUR
    SearchTerm: Mendoza
    TransportationZone:
    Language: DK
  - 
    CustomerID: 1234567890 
    CustomerName: Marvin Balane
    CustomerName2: Marvs
    Street: Dela Rosa
    City: Makati
    PostalCode: 1230
    Country: PH
    Currency: EUR
    SearchTerm: Balane
    TransportationZone:
    Language: DK
