#%RAML 1.0 DataType

type: object
properties: 
  CustomerID: string
  CustomerName1: string
  CustomerName2: string
  CustomerName3: string
  CustomerName4: string
  City: string
  District: string
  POBox: string
  PostalCode: string
  Region: string
  County: string
  CityCode: string
  Street: string
  Telephone: string
  Country: string
