#%RAML 1.0 NamedExample
value:

  - 
    CustomerID: 2345678901
    CustomerName: Raymond Mendoza
	Street: Dela Rosa
	City: Makati
	PostalCode: 1230
	Country: PH
	Telephone:
	AccountNumber:
	Email:
  - 
    CustomerID: 1234567890 
    CustomerName: Marvin Balane
	Street: Dela Rosa
	City: Makati
	PostalCode: 1230
	Country: PH
	Telephone:
	AccountNumber:
	Email:
