#%RAML 1.0 NamedExample
value:

  - 
    CustomerID: 2345678901
    CustomerName1: Raymond Mendoza
    CustomerName2: 
    CustomerName3: 
    CustomerName4: 
    City: Makati
    District: Pio Del Pilar
    POBox: 
    PostalCode: 1230
    Region: 
    County: 
    CityCode: 
    Street: Dela Rosa
    Telephone: 
    Country: PH
  - 
    CustomerID: 1234567890 
    CustomerName1: Marvin Balane
    CustomerName2: 
    CustomerName3: 
    CustomerName4: 
    City: 
    District: 
    POBox: 
    PostalCode: 
    Region: 
    County: 
    CityCode: 
    Street: 
    Telephone: 
    Country: PH
